"""FastAPI server for the RL env (SRE-backed) environment."""

import os
from pathlib import Path
from typing import List, Optional

from fastapi import Body, HTTPException
from pydantic import BaseModel

try:
    from openenv.core.env_server.http_server import create_app
except Exception as e:  # pragma: no cover
    raise ImportError(
        "openenv is required for the web interface. Install dependencies with '\n    uv sync\n'"
    ) from e

try:
    from ..models import SREAction, SREObservation, SREReward, SREState, SREStepInfo, SREStepResult, TaskSummary
    from .sre_environment import SREEnvironment
except ImportError:
    from models import SREAction, SREObservation, SREReward, SREState, SREStepInfo, SREStepResult, TaskSummary
    from server.sre_environment import SREEnvironment


# Configuration
RL_PACKAGE_ROOT = Path(__file__).resolve().parents[1]
FIXTURES_DIR = Path(os.getenv("OPENENV_FIXTURES_DIR", RL_PACKAGE_ROOT / "fixtures")).resolve()
WORKSPACE_ROOT = Path(os.getenv("OPENENV_WORKSPACE_ROOT", RL_PACKAGE_ROOT / "workspace")).resolve()
WORKSPACE_ROOT.mkdir(parents=True, exist_ok=True)
PORT = int(os.getenv("PORT", 8000))


class ResetRequest(BaseModel):
    task_id: Optional[str] = None


class OpenEnvSREEnvironment(SREEnvironment):
    """OpenEnv-compatible SRE env with path config from env vars."""

    def __init__(self):
        super().__init__(fixtures_dir=FIXTURES_DIR, workspace_root=WORKSPACE_ROOT)


app = create_app(
    OpenEnvSREEnvironment,
    SREAction,
    SREObservation,
    env_name="rl_env",
    max_concurrent_envs=1,
)

# Override autogenerated routes so API shape matches existing SRE endpoints.
app.router.routes = [
    route for route in app.router.routes
    if getattr(route, "path", None) not in ["/reset", "/step", "/state"]
]

GLOBAL_ENV = OpenEnvSREEnvironment()


def get_active_env() -> SREEnvironment:
    """Return active OpenEnv session env if available, else fallback env."""
    if hasattr(app.state, "env_manager"):
        envs = getattr(app.state.env_manager, "_envs", {})
        if envs:
            latest = list(envs.values())[-1]
            return getattr(latest, "env", latest)
    return GLOBAL_ENV


@app.get("/")
async def root():
    return {"message": "RL Env (SRE-backed) environment is running."}


@app.get("/health")
async def health():
    active_env = get_active_env()
    return {
        "status": "healthy",
        "rl_package_root": str(RL_PACKAGE_ROOT),
        "fixtures_dir": str(FIXTURES_DIR),
        "workspace_root": str(WORKSPACE_ROOT),
        "task_count": len(active_env.registry.list_summaries()),
    }


@app.get("/tasks", response_model=List[TaskSummary])
async def list_tasks():
    active_env = get_active_env()
    return active_env.registry.list_summaries()


@app.post("/reset", response_model=SREStepResult)
def reset(request: ResetRequest = Body(default_factory=ResetRequest)):
    active_env = get_active_env()
    task_id = request.task_id or active_env.registry.default_task_id()
    observation = active_env.reset(task_id)
    if observation.stderr.startswith("Error:"):
        raise HTTPException(status_code=400, detail=observation.stderr)
    metadata = observation.metadata if isinstance(observation.metadata, dict) else {}
    return SREStepResult(
        observation=observation,
        reward=SREReward(value=float(observation.reward or 0.0)),
        done=bool(observation.done),
        info=SREStepInfo(
            score=metadata.get("score"),
            message=metadata.get("message", f"Episode reset for task_id={task_id}"),
            last_action_error=metadata.get("last_action_error"),
        ),
    )


@app.post("/step", response_model=SREStepResult)
def step(action: SREAction):
    active_env = get_active_env()
    observation = active_env.step(action)
    metadata = observation.metadata if isinstance(observation.metadata, dict) else {}
    if observation.stderr.startswith("Error:") and not bool(observation.done):
        raise HTTPException(status_code=400, detail=observation.stderr)
    return SREStepResult(
        observation=observation,
        reward=SREReward(value=float(observation.reward or 0.0)),
        done=bool(observation.done),
        info=SREStepInfo(
            score=metadata.get("score"),
            message=metadata.get("message", ""),
            last_action_error=metadata.get("last_action_error"),
        ),
    )


@app.get("/state", response_model=Optional[SREState])
async def get_state():
    active_env = get_active_env()
    return active_env.get_api_state()


def main(host: str = "0.0.0.0", port: int = PORT):
    import uvicorn

    uvicorn.run(app, host=host, port=port)


if __name__ == "__main__":
    main()
